In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier

In [2]:
iris = datasets.load_iris()

In [3]:
feature = iris.data
labels = iris.target

In [4]:
print(feature[0],labels[0])

[5.1 3.5 1.4 0.2] 0


In [5]:
# training the classifier
clf = KNeighborsClassifier()
clf.fit(feature,labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [6]:
preds = clf.predict([[5.1 ,3.5, 1.4 ,0.2]])


In [7]:
preds

array([0])

In [8]:
preds = clf.predict([[8.90 ,3.5, 1.4 ,0.2]])

In [9]:
preds

array([0])